import path from "path"
import { Context, Effect, Layer } from "effect"
import { ObsidianVault } from "./vault"
import { Config } from "../config"
import { ConfigObsidian } from "../config/obsidian"
import { FSUtil } from "../fs-util"

export interface SessionData {
  readonly id: string
  readonly title: string
  readonly project: string
  readonly files: ReadonlyArray<string>
  readonly summary: string
  readonly tokens: number
  readonly timestamp: number
  readonly agent?: string
  readonly model?: string
}

export interface Interface {
  readonly syncSession: (session: SessionData) => Effect.Effect<void, never>
  readonly isEnabled: () => Effect.Effect<boolean, never>
}

export class Service extends Context.Service<Service, Interface>()("@octocode/ObsidianSessionSync") {}

function generateSessionMarkdown(session: SessionData): string {
  const date = new Date(session.timestamp)
  const formattedDate = date.toISOString().split("T")[0]
  const formattedTime = date.toLocaleTimeString()

  const filesList =
    session.files.length > 0
      ? session.files.map((f) => `- \`${f}\``).join("\n")
      : "- No files modified"

  return `---
created: ${date.toISOString()}
type: session
session_id: ${session.id}
project: ${session.project}
tokens: ${session.tokens}
files_modified: ${session.files.length}
agent: ${session.agent ?? "default"}
model: ${session.model ?? "unknown"}
---

# ${session.title}

**Date:** ${formattedDate} at ${formattedTime}
**Project:** ${session.project}
**Tokens Used:** ${session.tokens.toLocaleString()}
${session.agent ? `**Agent:** ${session.agent}` : ""}
${session.model ? `**Model:** ${session.model}` : ""}

## Summary

${session.summary || "No summary available"}

## Files Modified

${filesList}

---
*Auto-generated by OctoCode Obsidian Sync*
*Last updated: ${new Date().toISOString()}*
`
}

function generateProjectIndex(projectName: string, sessions: ReadonlyArray<SessionData>): string {
  const sorted = [...sessions].sort((a, b) => b.timestamp - a.timestamp)
  const sessionLinks = sorted
    .map((s) => `- [[${s.id}|${s.title}]] (${new Date(s.timestamp).toLocaleDateString()})`)
    .join("\n")

  const allFiles = new Set<string>()
  for (const s of sessions) {
    for (const f of s.files) allFiles.add(f)
  }
  const fileList = [...allFiles].sort().map((f) => `- \`${f}\``).join("\n")

  return `---
created: ${new Date(sorted[0]?.timestamp ?? Date.now()).toISOString()}
type: project-index
project: ${projectName}
total_sessions: ${sessions.length}
---

# ${projectName} - Session History

## Sessions (${sessions.length})

${sessionLinks || "No sessions recorded"}

## All Files Modified

${fileList || "No files recorded"}

---
*Auto-generated by OctoCode Obsidian Sync*
*Last updated: ${new Date().toISOString()}*
`
}

export const layer = Layer.effect(
  Service,
  Effect.gen(function* () {
    const vault = yield* ObsidianVault.Service
    const fs = yield* FSUtil.Service
    const config = yield* Config.Service

    const getObsidianConfig = Effect.fnUntraced(function* () {
      const entries = yield* config.entries()
      const last = entries.findLast(
        (e): e is { type: "document"; info: { obsidian?: ConfigObsidian.Info } } =>
          e.type === "document" && (e.info as any).obsidian !== undefined,
      )
      return (last?.info as any)?.obsidian as ConfigObsidian.Info | undefined
    })

    const isEnabled = Effect.fnUntraced(function* () {
      const oc = yield* getObsidianConfig()
      if (oc?.enabled === false) return false
      if (oc?.sync_sessions === false) return false
      return yield* vault.isEnabled()
    })

    const syncSession = Effect.fnUntraced(function* (session: SessionData) {
      const enabled = yield* isEnabled()
      if (!enabled) return

      const vaultPath = yield* vault.getVaultPath()
      if (!vaultPath) return

      const oc = yield* getObsidianConfig()
      const noteFolder = oc?.note_folder ?? "OctoCode"

      const sessionsDir = path.join(vaultPath, noteFolder, "Sessions")
      yield* fs.writeWithDirs(path.join(sessionsDir, `${session.id}.md`), generateSessionMarkdown(session)).pipe(
        Effect.catch(() => Effect.void),
      )

      const projectsDir = path.join(vaultPath, noteFolder, "Projects")
      const projectIndex = generateProjectIndex(session.project, [session])
      yield* fs.writeWithDirs(path.join(projectsDir, `${session.project}.md`), projectIndex).pipe(
        Effect.catch(() => Effect.void),
      )
    })

    return Service.of({
      syncSession,
      isEnabled,
    })
  }),
)

export * as ObsidianSessionSync from "./session-sync"
